# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target '卡片效果' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FlexLayout'
  pod 'RxSwift'
  pod 'RxCocoa','= 5.1.1'
  pod 'Alamofire'
  pod 'HandyJSON','~> 5.0.2' #解析
  pod 'Shimmer'
  pod 'XHLaunchAd'
  pod 'Moya'
  pod 'SDWebImage'

end
